# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import san_protocol_pb2 as san__protocol__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in san_protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShopperAssistantNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/san.ShopperAssistantNode/StreamTelemetry',
                request_serializer=san__protocol__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=san__protocol__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.StreamCommands = channel.unary_stream(
                '/san.ShopperAssistantNode/StreamCommands',
                request_serializer=san__protocol__pb2.CommandRequest.SerializeToString,
                response_deserializer=san__protocol__pb2.CommandResponse.FromString,
                _registered_method=True)


class ShopperAssistantNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTelemetry(self, request_iterator, context):
        """SAN pushes telemetry to Nikolai
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCommands(self, request, context):
        """Nikolai pushes commands to SAN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopperAssistantNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=san__protocol__pb2.TelemetryRequest.FromString,
                    response_serializer=san__protocol__pb2.TelemetryResponse.SerializeToString,
            ),
            'StreamCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCommands,
                    request_deserializer=san__protocol__pb2.CommandRequest.FromString,
                    response_serializer=san__protocol__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'san.ShopperAssistantNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('san.ShopperAssistantNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShopperAssistantNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/san.ShopperAssistantNode/StreamTelemetry',
            san__protocol__pb2.TelemetryRequest.SerializeToString,
            san__protocol__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/san.ShopperAssistantNode/StreamCommands',
            san__protocol__pb2.CommandRequest.SerializeToString,
            san__protocol__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
