# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: san_protocol.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'san_protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12san_protocol.proto\x12\x03san\"c\n\x10TelemetryRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x15\n\rcurrent_state\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"$\n\x11TelemetryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"N\n\x0f\x43ommandResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x17\n\x0fparameters_json\x18\x03 \x01(\t2\x99\x01\n\x14ShopperAssistantNode\x12\x42\n\x0fStreamTelemetry\x12\x15.san.TelemetryRequest\x1a\x16.san.TelemetryResponse(\x01\x12=\n\x0eStreamCommands\x12\x13.san.CommandRequest\x1a\x14.san.CommandResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'san_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYREQUEST']._serialized_start=27
  _globals['_TELEMETRYREQUEST']._serialized_end=126
  _globals['_TELEMETRYRESPONSE']._serialized_start=128
  _globals['_TELEMETRYRESPONSE']._serialized_end=164
  _globals['_COMMANDREQUEST']._serialized_start=166
  _globals['_COMMANDREQUEST']._serialized_end=199
  _globals['_COMMANDRESPONSE']._serialized_start=201
  _globals['_COMMANDRESPONSE']._serialized_end=279
  _globals['_SHOPPERASSISTANTNODE']._serialized_start=282
  _globals['_SHOPPERASSISTANTNODE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
